#' Game duration by order of magnitude of dictionary size
#'
#' This dataset contains the duration in moves of 500 simulated Begriffix games, and the corresponding number of words in the players' dictionaries. Both players shared one dictionary per game. For 5 different sizes (\code{10^(1:5)}), 100 games were generated. The start letters were randomly selected for each game from the human-generated ones. \code{\link{Derewo_Wortformen}} was used as full dictionary where the players got the nth start words.
#' @usage data(dict_oom)
#'
#' @format Dataset with 500 rows and 2 variables:
#' \describe{
#'   \item{words}{The number of words in the players' dictionaries.}
#'   \item{moves}{How many moves did the game reach}
#' }
#' @source Generated by simulation
#' @family simulation data
"dict_oom"